#!/bin/bash
if [[ ! -f sseutils64.nasm ]]; then cp ./64bit/sseutils64.nasm .; fi;
nasm -f elf64 ./64bit/sseutils64.nasm;
for f in $(ls ./64bit/*64omp.nasm); do
	nasm -f elf64 $f;
done;
gcc -m64 -msse  -O0 -no-pie -fopenmp ./64bit/sseutils64.o ./64bit/*64omp.o ./64bit/cfs64_omp.c -o ./64bit/cfs64omp -lm
