#!/bin/bash
if [[ ! -e ./32bit/sseutils32.o ]]; then nasm -f elf32 ./32bit/sseutils32.nasm; fi;
nasm -f elf32 ./32bit/cfs32omp.nasm
gcc -m32 -msse -O0 -no-pie -fopenmp ./32bit/sseutils32.o ./32bit/cfs32omp.o ./32bit/cfs32_omp.c -o ./32bit/cfs32omp -lm
pars="";
for arg; do pars=$pars" "$arg; done;
./32bit/cfs32omp $pars
