#!/bin/bash
if [[ ! -e sseutils32.o ]]; then nasm -f elf32 ./32bit/sseutils32.nasm; fi;
nasm -f elf32 ./32bit/cfs32.nasm
gcc -m32 -msse -O0 -no-pie ./32bit/sseutils32.o ./32bit/cfs32.o ./32bit/cfs32c.c -o ./32bit/cfs32c -lm
pars="";
for arg; do pars=$pars" "$arg; done;
./32bit/cfs32c $pars
